// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.uuid().primaryKey().name("game_id"),
  owner: __t.identity(),
  phase: __t.string(),
  roundNo: __t.u16().name("round_no"),
  maxRounds: __t.u16().name("max_rounds"),
  czar: __t.identity(),
  deadline: __t.timestamp(),
  createdAt: __t.timestamp().name("created_at"),
});
