// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ImportedPromptCard,
  ImportedAnswerCard,
} from "./types";

export default {
  packId: __t.uuid(),
  name: __t.string(),
  get promptCards() {
    return __t.array(ImportedPromptCard);
  },
  get answerCards() {
    return __t.array(ImportedAnswerCard);
  },
};
