// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  submissionId: __t.uuid().primaryKey().name("submission_id"),
  gameId: __t.uuid().name("game_id"),
  roundNo: __t.u16().name("round_no"),
  player: __t.identity(),
  submittedAt: __t.timestamp().name("submitted_at"),
  revealOrder: __t.u16().name("reveal_order"),
  isWinner: __t.bool().name("is_winner"),
});
