// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AnswerCards = __t.object("AnswerCards", {
  answerId: __t.uuid(),
  packId: __t.uuid(),
  cardRef: __t.u32(),
});
export type AnswerCards = __Infer<typeof AnswerCards>;

export const GameAnswerDeck = __t.object("GameAnswerDeck", {
  id: __t.u64(),
  gameId: __t.uuid(),
  order: __t.u32(),
  answerId: __t.uuid(),
  drawn: __t.bool(),
});
export type GameAnswerDeck = __Infer<typeof GameAnswerDeck>;

export const GamePacks = __t.object("GamePacks", {
  id: __t.u64(),
  gameId: __t.uuid(),
  packId: __t.uuid(),
  addedBy: __t.identity(),
  addedAt: __t.timestamp(),
});
export type GamePacks = __Infer<typeof GamePacks>;

export const GamePlayers = __t.object("GamePlayers", {
  id: __t.u64(),
  gameId: __t.uuid(),
  player: __t.identity(),
  displayName: __t.string(),
  seat: __t.u16(),
  joinedAt: __t.timestamp(),
});
export type GamePlayers = __Infer<typeof GamePlayers>;

export const GamePromptDeck = __t.object("GamePromptDeck", {
  id: __t.u64(),
  gameId: __t.uuid(),
  order: __t.u32(),
  promptId: __t.uuid(),
  drawn: __t.bool(),
});
export type GamePromptDeck = __Infer<typeof GamePromptDeck>;

export const Games = __t.object("Games", {
  gameId: __t.uuid(),
  owner: __t.identity(),
  phase: __t.string(),
  roundNo: __t.u16(),
  maxRounds: __t.u16(),
  czar: __t.identity(),
  deadline: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type Games = __Infer<typeof Games>;

export const HandCards = __t.object("HandCards", {
  id: __t.u64(),
  gameId: __t.uuid(),
  player: __t.identity(),
  answerId: __t.uuid(),
  slot: __t.u16(),
  dealtAt: __t.timestamp(),
});
export type HandCards = __Infer<typeof HandCards>;

export const ImportedAnswerCard = __t.object("ImportedAnswerCard", {
  answerId: __t.uuid(),
  cardRef: __t.u32(),
});
export type ImportedAnswerCard = __Infer<typeof ImportedAnswerCard>;

export const ImportedPromptCard = __t.object("ImportedPromptCard", {
  promptId: __t.uuid(),
  cardRef: __t.u32(),
  blanks: __t.u8(),
});
export type ImportedPromptCard = __Infer<typeof ImportedPromptCard>;

export const Packs = __t.object("Packs", {
  packId: __t.uuid(),
  name: __t.string(),
});
export type Packs = __Infer<typeof Packs>;

export const PromptCards = __t.object("PromptCards", {
  promptId: __t.uuid(),
  packId: __t.uuid(),
  cardRef: __t.u32(),
  blanks: __t.u8(),
});
export type PromptCards = __Infer<typeof PromptCards>;

export const Rounds = __t.object("Rounds", {
  id: __t.u64(),
  gameId: __t.uuid(),
  roundNo: __t.u16(),
  promptId: __t.uuid(),
  czar: __t.identity(),
  startedAt: __t.timestamp(),
});
export type Rounds = __Infer<typeof Rounds>;

export const Scores = __t.object("Scores", {
  id: __t.u64(),
  gameId: __t.uuid(),
  player: __t.identity(),
  points: __t.u16(),
});
export type Scores = __Infer<typeof Scores>;

export const SubmissionCards = __t.object("SubmissionCards", {
  id: __t.u64(),
  submissionId: __t.uuid(),
  slotIndex: __t.u8(),
  answerId: __t.uuid(),
});
export type SubmissionCards = __Infer<typeof SubmissionCards>;

export const Submissions = __t.object("Submissions", {
  submissionId: __t.uuid(),
  gameId: __t.uuid(),
  roundNo: __t.u16(),
  player: __t.identity(),
  submittedAt: __t.timestamp(),
  revealOrder: __t.u16(),
  isWinner: __t.bool(),
});
export type Submissions = __Infer<typeof Submissions>;

